/**
 * AUTO-GENERATED by scripts/generateImageManifest.ts — do not edit by hand.
 * Regenerate with `npm run images:scan` (also runs automatically before dev/build)
 * whenever files under public/images/products/ change.
 */
export const PRODUCT_IMAGE_MANIFEST: Record<string, Record<string, Record<string, string[]>>> = {
  "men": {
    "Belts": {
      "BL001": [
        "BL001-1.jpg",
        "BL001-2.jpg",
        "BL001-3.jpg"
      ],
      "BL002": [
        "BL002-1.jpg",
        "BL002-2.jpg"
      ],
      "BL003": [
        "BL003-1.jpg",
        "BL003-2.jpg"
      ],
      "BL004": [
        "BL004-1.jpg",
        "BL004-2.jpg",
        "BL004-3.jpg"
      ]
    },
    "Blazers": {
      "BZ001": [
        "BZ001-1.jpg",
        "BZ001-2.jpg",
        "BZ001-3.jpg",
        "BZ001-4.jpg",
        "BZ001-5.jpg",
        "BZ001-6.jpg"
      ],
      "BZ002": [
        "BZ002-1.jpg",
        "BZ002-2.jpg",
        "BZ002-3.jpg",
        "BZ002-4.jpg",
        "BZ002-5.jpg"
      ],
      "BZ003": [
        "BZ003-1.jpg",
        "BZ003-2.jpg",
        "BZ003-3.jpg",
        "BZ003-4.jpg",
        "BZ003-5.jpg",
        "BZ003-6.jpg"
      ],
      "BZ004": [
        "BZ004-1.jpg",
        "BZ004-2.jpg",
        "BZ004-3.jpg"
      ],
      "BZ005": [
        "BZ005-1.jpg",
        "BZ005-2.jpg",
        "BZ005-3.jpg",
        "BZ005-4.jpg",
        "BZ005-5.jpg"
      ],
      "BZ006": [
        "BZ006-1.jpg",
        "BZ006-2.jpg",
        "BZ006-3.jpg",
        "BZ006-4.jpg",
        "BZ006-5.jpg",
        "BZ006-6.jpg"
      ]
    },
    "Cargo Pants": {
      "CP001": [
        "CP001-1.jpg",
        "CP001-2.jpg",
        "CP001-3.jpg",
        "CP001-4.jpg",
        "CP001-5.jpg",
        "CP001-6.jpg"
      ],
      "CP002": [
        "CP002-1.jpg",
        "CP002-2.jpg",
        "CP002-3.jpg"
      ],
      "CP003": [
        "CP003-1.jpg",
        "CP003-2.jpg",
        "CP003-3.jpg",
        "CP003-4.jpg",
        "CP003-5.jpg"
      ],
      "CP004": [
        "CP004-1.jpg",
        "CP004-2.jpg",
        "CP004-3.jpg",
        "CP004-4.jpg",
        "CP004-5.jpg"
      ],
      "CP005": [
        "CP005-1.jpg",
        "CP005-2.jpg",
        "CP005-3.jpg",
        "CP005-4.jpg",
        "CP005-5.jpg"
      ],
      "CP006": [
        "CP006-1.jpg",
        "CP006-2.jpg",
        "CP006-3.jpg",
        "CP006-4.jpg",
        "CP006-5.jpg",
        "CP006-6.jpg"
      ],
      "CP007": [
        "CP007-1.jpg",
        "CP007-2.jpg",
        "CP007-3.jpg",
        "CP007-4.jpg"
      ],
      "CP008": [
        "CP008-1.jpg",
        "CP008-2.jpg",
        "CP008-3.jpg",
        "CP008-4.jpg",
        "CP008-5.jpg",
        "CP008-6.jpg"
      ],
      "CP009": [
        "CP009-1.jpg",
        "CP009-2.jpg",
        "CP009-3.jpg",
        "CP009-4.jpg",
        "CP009-5.jpg",
        "CP009-6.jpg"
      ],
      "CP010": [
        "CP010-1.jpg",
        "CP010-2.jpg",
        "CP010-3.jpg",
        "CP010-4.jpg",
        "CP010-5.jpg",
        "CP010-6.jpg"
      ]
    },
    "casual-shirts": {
      "CS001": [
        "CS001-1.jpg",
        "CS001-2.jpg",
        "CS001-3.jpg",
        "CS001-4.jpg"
      ],
      "CS002": [
        "CS002-1.jpg",
        "CS002-2.jpg",
        "CS002-3.jpg",
        "CS002-4.jpg",
        "CS002-5.jpg",
        "CS002-6.jpg"
      ],
      "CS003": [
        "CS003-1.jpg",
        "CS003-2.jpg",
        "CS003-3.jpg",
        "CS003-4.jpg",
        "CS003-5.jpg"
      ],
      "CS004": [
        "CS004-1.jpg",
        "CS004-2.jpg",
        "CS004-3.jpg",
        "CS004-4.jpg",
        "CS004-5.jpg"
      ],
      "CS005": [
        "CS005-1.jpg",
        "CS005-2.jpg",
        "CS005-3.jpg",
        "CS005-4.jpg",
        "CS005-5.jpg"
      ],
      "CS006": [
        "CS006-1.jpg",
        "CS006-2.jpg",
        "CS006-3.jpg",
        "CS006-4.jpg"
      ],
      "CS007": [
        "CS007-1.jpg",
        "CS007-2.jpg",
        "CS007-3.jpg",
        "CS007-4.jpg",
        "CS007-5.jpg",
        "CS007-6.jpg"
      ]
    },
    "checked-shirts": {
      "CHS001": [
        "CHS001-1.jpg",
        "CHS001-2.jpg",
        "CHS001-3.jpg",
        "CHS001-4.jpg",
        "CHS001-5.jpg",
        "CHS001-6.jpg",
        "CHS001-7.jpg"
      ],
      "CHS002": [
        "CHS002-1.jpg",
        "CHS002-2.jpg",
        "CHS002-3.jpg",
        "CHS002-4.jpg",
        "CHS002-5.jpg",
        "CHS002-6.jpg"
      ],
      "CHS003": [
        "CHS003-1.jpg",
        "CHS003-2.jpg",
        "CHS003-3.jpg",
        "CHS003-4.jpg",
        "CHS003-5.jpg",
        "CHS003-6.jpg"
      ],
      "CHS004": [
        "CHS004-1.jpg",
        "CHS004-2.jpg",
        "CHS004-3.jpg",
        "CHS004-4.jpg",
        "CHS004-5.jpg",
        "CHS004-6.jpg"
      ],
      "CHS005": [
        "CHS005-1.jpg",
        "CHS005-2.jpg",
        "CHS005-3.jpg",
        "CHS005-4.jpg",
        "CHS005-5.jpg",
        "CHS005-6.jpg"
      ],
      "CHS006": [
        "CHS006-1.jpg",
        "CHS006-2.jpg",
        "CHS006-3.jpg",
        "CHS006-4.jpg",
        "CHS006-5.jpg"
      ],
      "CHS007": [
        "CHS007-1.jpg",
        "CHS007-2.jpg",
        "CHS007-3.jpg",
        "CHS007-4.jpg",
        "CHS007-5.jpg"
      ],
      "CHS008": [
        "CHS008-1.jpg",
        "CHS008-2.jpg",
        "CHS008-3.jpg",
        "CHS008-4.jpg",
        "CHS008-5.jpg",
        "CHS008-6.jpg"
      ],
      "CHS009": [
        "CHS009-1.jpg",
        "CHS009-2.jpg",
        "CHS009-3.jpg",
        "CHS009-4.jpg",
        "CHS009-5.jpg"
      ],
      "CHS010": [
        "CHS010-1.jpg",
        "CHS010-2.jpg",
        "CHS010-3.jpg",
        "CHS010-4.jpg",
        "CHS010-5.jpg",
        "CHS010-6.jpg"
      ],
      "CHS011": [
        "CHS011-1.jpg",
        "CHS011-2.jpg",
        "CHS011-3.jpg",
        "CHS011-4.jpg",
        "CHS011-5.jpg",
        "CHS011-6.jpg"
      ],
      "CHS012": [
        "CHS012-1.jpg",
        "CHS012-2.jpg",
        "CHS012-3.jpg",
        "CHS012-4.jpg",
        "CHS012-5.jpg"
      ],
      "CHS013": [
        "CHS013-1.jpg",
        "CHS013-2.jpg",
        "CHS013-3.jpg",
        "CHS013-4.jpg",
        "CHS013-5.jpg"
      ],
      "CHS014": [
        "CHS014-1.jpg",
        "CHS014-2.jpg",
        "CHS014-3.jpg",
        "CHS014-4.jpg",
        "CHS014-5.jpg"
      ],
      "CHS016": [
        "CHS016-1.jpg",
        "CHS016-2.jpg",
        "CHS016-3.jpg",
        "CHS016-4.jpg",
        "CHS016-5.jpg",
        "CHS016-6.jpg"
      ],
      "CHS017": [
        "CHS017-1.jpg",
        "CHS017-2.jpg",
        "CHS017-3.jpg",
        "CHS017-4.jpg",
        "CHS017-5.jpg",
        "CHS017-6.jpg"
      ],
      "CHS018": [
        "CHS018-1.jpg",
        "CHS018-2.jpg",
        "CHS018-3.jpg",
        "CHS018-4.jpg",
        "CHS018-5.jpg"
      ],
      "CHS019": [
        "CHS019-1.jpg",
        "CHS019-2.jpg",
        "CHS019-3.jpg",
        "CHS019-4.jpg",
        "CHS019-5.jpg",
        "CHS019-6.jpg",
        "CHS019-7.jpg"
      ],
      "CHS020": [
        "CHS020-1.jpg",
        "CHS020-2.jpg",
        "CHS020-3.jpg",
        "CHS020-4.jpg",
        "CHS020-5.jpg"
      ],
      "CHS021": [
        "CHS021-1.jpg",
        "CHS021-2.jpg",
        "CHS021-3.jpg",
        "CHS021-4.jpg",
        "CHS021-5.jpg"
      ],
      "CHS022": [
        "CHS022-1.jpg",
        "CHS022-2.jpg",
        "CHS022-3.jpg",
        "CHS022-4.jpg",
        "CHS022-5.jpg"
      ],
      "CHS023": [
        "CHS023-1.jpg",
        "CHS023-2.jpg",
        "CHS023-3.jpg",
        "CHS023-4.jpg",
        "CHS023-5.jpg",
        "CHS023-6.jpg"
      ],
      "CHS024": [
        "CHS024-1.jpg",
        "CHS024-2.jpg",
        "CHS024-3.jpg",
        "CHS024-4.jpg",
        "CHS024-5.jpg"
      ],
      "CHS025": [
        "CHS025-1.jpg",
        "CHS025-2.jpg",
        "CHS025-3.jpg",
        "CHS025-4.jpg",
        "CHS025-5.jpg",
        "CHS025-6.jpg"
      ],
      "CHS026": [
        "CHS026-1.jpg",
        "CHS026-2.jpg",
        "CHS026-3.jpg",
        "CHS026-4.jpg"
      ],
      "CHS027": [
        "CHS027-1.jpg",
        "CHS027-2.jpg",
        "CHS027-3.jpg",
        "CHS027-4.jpg",
        "CHS027-5.jpg"
      ],
      "CHS028": [
        "CHS028-1.jpg",
        "CHS028-2.jpg",
        "CHS028-3.jpg",
        "CHS028-4.jpg",
        "CHS028-5.jpg",
        "CHS028-6.jpg"
      ],
      "CHS029": [
        "CHS029-1.jpg",
        "CHS029-2.jpg",
        "CHS029-3.jpg",
        "CHS029-4.jpg",
        "CHS029-5.jpg"
      ],
      "CHS030": [
        "CHS030-1.jpg",
        "CHS030-2.jpg"
      ]
    },
    "Cotton-Shirts": {
      "CT001": [
        "CT001-1.jpg",
        "CT001-2.jpg",
        "CT001-3.jpg",
        "CT001-4.jpg",
        "CT001-5.jpg"
      ],
      "CT002": [
        "CT002-1.jpg",
        "CT002-2.jpg",
        "CT002-3.jpg",
        "CT002-4.jpg",
        "CT002-5.jpg",
        "CT002-6.jpg"
      ],
      "CT003": [
        "CT003-1.jpg",
        "CT003-2.jpg",
        "CT003-3.jpg",
        "CT003-4.jpg"
      ],
      "CT004": [
        "CT004-1.jpg",
        "CT004-2.jpg",
        "CT004-3.jpg",
        "CT004-4.jpg",
        "CT004-5.jpg"
      ],
      "CT005": [
        "CT005-1.jpg",
        "CT005-2.jpg",
        "CT005-3.jpg",
        "CT005-4.jpg",
        "CT005-5.jpg"
      ]
    },
    "Formal Pants": {
      "FP001": [
        "FP001-1.jpg",
        "FP001-2.jpg",
        "FP001-3.jpg",
        "FP001-4.jpg"
      ],
      "FP002": [
        "FP002-1.jpg",
        "FP002-2.jpg",
        "FP002-3.jpg",
        "FP002-4.jpg",
        "FP002-5.jpg"
      ],
      "FP003": [
        "FP003-1.jpg",
        "FP003-2.jpg",
        "FP003-3.jpg",
        "FP003-4.jpg"
      ],
      "FP004": [
        "FP004-1.jpg",
        "FP004-2.jpg",
        "FP004-3.jpg",
        "FP004-4.jpg"
      ],
      "FP005": [
        "FP005-1.jpg",
        "FP005-2.jpg",
        "FP005-3.jpg",
        "FP005-4.jpg",
        "FP005-5.jpg"
      ],
      "FP006": [
        "FP006-1.jpg",
        "FP006-2.jpg",
        "FP006-3.jpg",
        "FP006-4.jpg",
        "FP006-5.jpg"
      ],
      "FP007": [
        "FP007-1.jpg",
        "FP007-2.jpg",
        "FP007-3.jpg",
        "FP007-4.jpg"
      ],
      "FP008": [
        "FP008-1.jpg",
        "FP008-2.jpg",
        "FP008-3.jpg",
        "FP008-4.jpg"
      ],
      "FP009": [
        "FP009-1.jpg",
        "FP009-2.jpg",
        "FP009-3.jpg",
        "FP009-4.jpg"
      ],
      "FP010": [
        "FP010-1.jpg",
        "FP010-2.jpg",
        "FP010-3.jpg",
        "FP010-4.jpg"
      ],
      "FP011": [
        "FP011-1.jpg",
        "FP011-2.jpg",
        "FP011-3.jpg",
        "FP011-4.jpg"
      ],
      "FP012": [
        "FP012-1.jpg",
        "FP012-2.jpg",
        "FP012-3.jpg",
        "FP012-4.jpg",
        "FP012-5.jpg"
      ]
    },
    "formal-shirts": {
      "FS001": [
        "FS001-1.webp",
        "FS001-2.webp",
        "FS001-3.webp",
        "FS001-4.webp"
      ],
      "FS002": [
        "FS002-1.webp",
        "FS002-2.webp",
        "FS002-3.webp",
        "FS002-4.webp"
      ],
      "FS003": [
        "FS003-1.webp",
        "FS003-2.webp",
        "FS003-3.webp",
        "FS003-4.webp",
        "FS003-5.webp",
        "FS003-6.webp"
      ],
      "FS004": [
        "FS004-1.jpeg",
        "FS004-2.jpeg",
        "FS004-3.jpeg",
        "FS004-4.jpeg"
      ],
      "FS007": [
        "FS007-1.jpg",
        "FS007-2.jpg",
        "FS007-3.jpg",
        "FS007-4.jpg",
        "FS007-5.jpg"
      ],
      "FS008": [
        "FS008-1.jpg",
        "FS008-2.jpg",
        "FS008-3.jpg",
        "FS008-4.jpg"
      ],
      "FS009": [
        "FS009-1.jpg",
        "FS009-2.jpg",
        "FS009-3.jpg",
        "FS009-4.jpg",
        "FS009-5.jpg"
      ],
      "FS010": [
        "FS010-1.jpg",
        "FS010-2.jpg",
        "FS010-3.jpg",
        "FS010-4.jpg",
        "FS010-5.jpg"
      ],
      "FS011": [
        "FS011-1.jpg",
        "FS011-2.jpg",
        "FS011-3.jpg",
        "FS011-4.jpg",
        "FS011-5.jpg",
        "FS011-6.jpg"
      ],
      "FS014": [
        "FS014-1.jpg",
        "FS014-2.jpg",
        "FS014-3.jpg",
        "FS014-4.jpg",
        "FS014-5.jpg"
      ],
      "FS015": [
        "FS015-1.jpg",
        "FS015-2.jpg",
        "FS015-3.jpg",
        "FS015-4.jpg"
      ],
      "FS016": [
        "FS016-1.jpg",
        "FS016-2.jpg",
        "FS016-3.jpg",
        "FS016-4.jpg",
        "FS016-5.png",
        "FS016-6.png"
      ],
      "FS017": [
        "FS017-2.jpg",
        "FS017-3.jpg",
        "FS017-4.jpg",
        "FS017-5.jpg"
      ],
      "FS019": [
        "FS019-1.jpg",
        "FS019-2.jpg",
        "FS019-3.jpg"
      ],
      "FS020": [
        "FS020-1.jpg",
        "FS020-2.jpg",
        "FS020-3.jpg",
        "FS020-4.jpg"
      ],
      "FS021": [
        "FS021-1.webp",
        "FS021-2.webp",
        "FS021-3.webp"
      ],
      "FS023": [
        "FS023-1.png",
        "FS023-2.png",
        "FS023-3.png",
        "FS023-4.png",
        "FS023-5.png",
        "FS023-6.png"
      ],
      "FS024": [
        "FS024-1.png",
        "FS024-2.png",
        "FS024-3.png",
        "FS024-4.png",
        "FS024-5.png"
      ],
      "FS025": [
        "FS025-1.png",
        "FS025-2.png",
        "FS025-3.png",
        "FS025-4.png"
      ],
      "FS026": [
        "FS026-1.png",
        "FS026-2.png",
        "FS026-3.png"
      ],
      "FS027": [
        "FS027-1.png",
        "FS027-2.png",
        "FS027-3.png",
        "FS027-4.png",
        "FS027-5.png",
        "FS027-6.png"
      ],
      "FS028": [
        "FS028-1.png",
        "FS028-2.png",
        "FS028-3.png",
        "FS028-4.png",
        "FS028-5.png"
      ],
      "FS029": [
        "FS029-1.png",
        "FS029-2.png",
        "FS029-3.png",
        "FS029-4.png",
        "FS029-5.png",
        "FS029-6.png"
      ],
      "FS030": [
        "FS030-1.png",
        "FS030-2.png",
        "FS030-3.png",
        "FS030-4.png",
        "FS030-5.png"
      ],
      "FS031": [
        "FS031-1.jpg",
        "FS031-2.jpg",
        "FS031-3.jpg",
        "FS031-4.jpg",
        "FS031-5.jpg",
        "FS031-6.jpg"
      ],
      "FS032": [
        "FS032-1.jpg",
        "FS032-2.jpg",
        "FS032-3.jpg",
        "FS032-4.jpg",
        "FS032-5.jpg"
      ],
      "FS033": [
        "FS033-1.jpg",
        "FS033-2.jpg",
        "FS033-3.jpg",
        "FS033-4.jpg",
        "FS033-5.jpg",
        "FS033-6.jpg"
      ],
      "FS034": [
        "FS034-1.jpg",
        "FS034-2.jpg",
        "FS034-3.jpg",
        "FS034-4.jpg",
        "FS034-5.jpg",
        "FS034-6.jpg"
      ],
      "FS035": [
        "FS035-1.jpg",
        "FS035-2.jpg",
        "FS035-3.jpg",
        "FS035-4.jpg",
        "FS035-5.jpg",
        "FS035-6.jpg"
      ],
      "FS036": [
        "FS036-1.jpg",
        "FS036-2.jpg",
        "FS036-3.jpg",
        "FS036-4.jpg",
        "FS036-5.jpg",
        "FS036-6.jpg",
        "FS036-7.jpg"
      ],
      "FS037": [
        "FS037-1.jpg",
        "FS037-2.jpg",
        "FS037-3.jpg",
        "FS037-4.jpg",
        "FS037-5.jpg",
        "FS037-6.jpg",
        "FS037-7.jpg"
      ],
      "FS038": [
        "FS038-1.jpg",
        "FS038-2.jpg",
        "FS038-3.jpg",
        "FS038-4.jpg",
        "FS038-5.jpg",
        "FS038-6.jpg"
      ],
      "FS039": [
        "FS039-1.jpg",
        "FS039-2.jpg",
        "FS039-3.jpg",
        "FS039-4.jpg",
        "FS039-5.jpg",
        "FS039-6.jpg",
        "FS039-7.jpg"
      ],
      "FS040": [
        "FS040-1.jpg",
        "FS040-2.jpg",
        "FS040-3.jpg",
        "FS040-4.jpg",
        "FS040-5.jpg",
        "FS040-6.jpg",
        "FS040-7.jpg"
      ],
      "FS041": [
        "FS041-1.jpg",
        "FS041-2.jpg",
        "FS041-3.jpg",
        "FS041-4.jpg",
        "FS041-5.jpg",
        "FS041-6.jpg",
        "FS041-7.jpg"
      ],
      "FS042": [
        "FS042-1.jpg",
        "FS042-2.jpg",
        "FS042-3.jpg",
        "FS042-4.jpg",
        "FS042-5.jpg",
        "FS042-6.jpg",
        "FS042-7.jpg"
      ],
      "FS043": [
        "FS043-1.jpg",
        "FS043-2.jpg",
        "FS043-3.jpg",
        "FS043-4.jpg",
        "FS043-5.jpg",
        "FS043-6.jpg"
      ],
      "FS044": [
        "FS044-1.jpg",
        "FS044-2.jpg",
        "FS044-3.jpg",
        "FS044-4.jpg"
      ],
      "FS045": [
        "FS045-1.jpg",
        "FS045-3.jpg",
        "FS045-4.jpg",
        "FS045-5.jpg"
      ],
      "FS046": [
        "FS046-1.jpg",
        "FS046-2.jpg",
        "FS046-3.jpg",
        "FS046-4.jpg",
        "FS046-5.jpg"
      ],
      "FS047": [
        "FS047-1.jpg",
        "FS047-2.jpg",
        "FS047-3.jpg",
        "FS047-4.jpg"
      ],
      "FS048": [
        "FS048-1.jpg",
        "FS048-2.jpg",
        "FS048-3.jpg",
        "FS048-4.jpg"
      ],
      "FS049": [
        "FS049-1.jpg",
        "FS049-2.jpg",
        "FS049-3.jpg",
        "FS049-4.jpg",
        "FS049-5.jpg",
        "FS049-6.jpg"
      ],
      "FS050": [
        "FS050-1.jpg",
        "FS050-2.jpg",
        "FS050-3.jpg",
        "FS050-5.jpg"
      ],
      "FS051": [
        "FS051-1.jpg",
        "FS051-2.jpg",
        "FS051-3.jpg",
        "FS051-4.jpg",
        "FS051-5.jpg"
      ],
      "FS052": [
        "FS052-1.jpg",
        "FS052-2.jpg",
        "FS052-3.jpg",
        "FS052-4.jpg"
      ],
      "FS053": [
        "FS053-1.jpg",
        "FS053-2.jpg",
        "FS053-4.jpg",
        "FS053-5.jpg",
        "FS053-6.jpg"
      ],
      "FS054": [
        "FS054-1.jpg",
        "FS054-2.jpg",
        "FS054-3.jpg",
        "FS054-4.jpg"
      ],
      "FS055": [
        "FS055-1.jpg",
        "FS055-2.jpg",
        "FS055-3.jpg",
        "FS055-4.jpg",
        "FS055-5.jpg",
        "FS055-6.jpg"
      ],
      "FS056": [
        "FS056-1.jpg",
        "FS056-2.jpg",
        "FS056-3.jpg",
        "FS056-4.jpg",
        "FS056-5.jpg",
        "FS056-6.jpg"
      ],
      "FS057": [
        "FS057-1.jpg",
        "FS057-2.jpg",
        "FS057-3.jpg",
        "FS057-4.jpg",
        "FS057-5.jpg",
        "FS057-6.jpg",
        "FS057-7.jpg"
      ],
      "FS058": [
        "FS058-1.jpg",
        "FS058-3.jpg",
        "FS058-4.jpg"
      ],
      "FS059": [
        "FS059-1.jpg",
        "FS059-2.jpg",
        "FS059-3.jpg",
        "FS059-4.jpg",
        "FS059-5.jpg",
        "FS059-6.jpg",
        "FS059-8.jpg"
      ],
      "FS060": [
        "FS060-1.jpg",
        "FS060-2.jpg",
        "FS060-3.jpg",
        "FS060-4.jpg"
      ],
      "FS061": [
        "FS061-1.jpg",
        "FS061-2.jpg",
        "FS061-3.jpg"
      ],
      "FS062": [
        "FS062-1.jpg",
        "FS062-2.jpg",
        "FS062-3.jpg"
      ],
      "FS063": [
        "FS063-1.jpg",
        "FS063-2.jpg",
        "FS063-3.jpg",
        "FS063-4.jpg",
        "FS063-5.jpg"
      ],
      "FS064": [
        "FS064-1.jpg",
        "FS064-2.jpg",
        "FS064-3.jpg",
        "FS064-4.jpg"
      ],
      "FS065": [
        "FS065-1.jpg",
        "FS065-2.jpg",
        "FS065-3.jpg",
        "FS065-4.jpg",
        "FS065-5.jpg"
      ],
      "FS066": [
        "FS066-1.jpg",
        "FS066-2.jpg",
        "FS066-3.jpg",
        "FS066-4.jpg",
        "FS066-5.jpg",
        "FS066-6.jpg"
      ],
      "FS067": [
        "FS067-1.jpg",
        "FS067-2.jpg",
        "FS067-3.jpg",
        "FS067-4.jpg",
        "FS067-5.jpg"
      ],
      "FS068": [
        "FS068-1.jpg",
        "FS068-2.jpg",
        "FS068-3.jpg",
        "FS068-4.jpg"
      ],
      "FS069": [
        "FS069-1.jpg",
        "FS069-2.jpg",
        "FS069-3.jpg",
        "FS069-4.jpg",
        "FS069-5.jpg"
      ],
      "FS070": [
        "FS070-1.jpg",
        "FS070-2.jpg",
        "FS070-3.jpg",
        "FS070-4.jpg",
        "FS070-5.jpg",
        "FS070-6.jpg",
        "FS070-7.jpg"
      ],
      "FS071": [
        "FS071-1.jpg",
        "FS071-2.jpg",
        "FS071-3.jpg",
        "FS071-4.jpg",
        "FS071-5.jpg"
      ],
      "FS072": [
        "FS072-1.jpg",
        "FS072-2.jpg",
        "FS072-3.jpg",
        "FS072-4.jpg",
        "FS072-5.jpg"
      ],
      "FS073": [
        "FS073-1.jpg",
        "FS073-2.jpg",
        "FS073-3.jpg",
        "FS073-4.jpg",
        "FS073-5.jpg",
        "FS073-6.jpg"
      ]
    },
    "Henley T-Shirts": {
      "HT001": [
        "HT001-1.jpg",
        "HT001-2.jpg",
        "HT001-3.jpg",
        "HT001-4.jpg",
        "HT001-5.jpg"
      ],
      "HT002": [
        "HT002-1.jpg",
        "HT002-2.jpg",
        "HT002-3.jpg",
        "HT002-4.jpg",
        "HT002-5.jpg",
        "HT002-6.jpg"
      ],
      "HT003": [
        "HT003-1.jpg",
        "HT003-2.jpg",
        "HT003-3.jpg",
        "HT003-4.jpg",
        "HT003-5.jpg"
      ],
      "HT004": [
        "HT004-1.jpg",
        "HT004-2.jpg",
        "HT004-3.jpg",
        "HT004-4.jpg",
        "HT004-5.jpg",
        "HT004-6.jpg"
      ],
      "HT005": [
        "HT005-1.jpg",
        "HT005-2.jpg",
        "HT005-3.jpg",
        "HT005-4.jpg",
        "HT005-5.jpg"
      ],
      "HT006": [
        "HT006-1.jpg",
        "HT006-2.jpg",
        "HT006-3.jpg",
        "HT006-4.jpg",
        "HT006-5.jpg"
      ]
    },
    "hoodies": {
      "HD001": [
        "HD001-1.jpg",
        "HD001.webp",
        "HD001-2.jpg",
        "HD001-3.jpg",
        "HD001-4.jpg",
        "HD001-5.jpg"
      ],
      "HD002": [
        "HD002-1.jpg",
        "HD002-2.jpg",
        "HD002-3.jpg",
        "HD002-4.jpg",
        "HD002-5.jpg"
      ],
      "HD003": [
        "HD003-1.jpg",
        "HD003-2.jpg",
        "HD003-3.jpg"
      ],
      "HD004": [
        "HD004-1.jpg",
        "HD004-2.jpg",
        "HD004-3.jpg"
      ],
      "HD005": [
        "HD005-1.jpg",
        "HD005-2.jpg",
        "HD005-3.jpg",
        "HD005-4.jpg",
        "HD005-5.jpg"
      ],
      "HD006": [
        "HD006-1.jpg",
        "HD006-2.jpg",
        "HD006-3.jpg",
        "HD006-4.jpg"
      ]
    },
    "Innerwear": {
      "IW001": [
        "IW001-1.jpg",
        "IW001-2.jpg"
      ],
      "IW002": [
        "IW002-1.jpg",
        "IW002-2.jpg"
      ],
      "IW003": [
        "IW003-1.jpg",
        "IW003-2.jpg"
      ]
    },
    "jackets": {
      "JK001": [
        "JK001-1.jpg",
        "JK001-2.jpg",
        "JK001-3.jpg",
        "JK001-4.jpg",
        "JK001-5.jpg"
      ],
      "JK002": [
        "JK002-1.jpg",
        "JK002-2.jpg",
        "JK002-3.jpg",
        "JK002-4.jpg"
      ],
      "JK003": [
        "JK003-1.jpg",
        "JK003-2.jpg",
        "JK003-3.jpg",
        "JK003-4.jpg"
      ],
      "JK004": [
        "JK004-1.jpg",
        "JK004-2.jpg",
        "JK004-3.jpg"
      ],
      "JK005": [
        "JK005-1.jpg",
        "JK005-2.jpg",
        "JK005-3.jpg",
        "JK005-4.jpg"
      ],
      "JK006": [
        "JK006-1.jpg",
        "JK006-2.jpg"
      ]
    },
    "jeans": {
      "JN001": [
        "JN001.webp"
      ]
    },
    "Joggers": {
      "JG001": [
        "JG001-1.jpg",
        "JG001-2.jpg",
        "JG001-3.jpg",
        "JG001-4.jpg",
        "JG001-5.jpg"
      ],
      "JG002": [
        "JG002-1.jpg",
        "JG002-2.jpg",
        "JG002-3.jpg",
        "JG002-4.jpg"
      ],
      "JG003": [
        "JG003-1.jpg",
        "JG003-2.jpg",
        "JG003-3.jpg",
        "JG003-4.jpg",
        "JG003-5.jpg"
      ],
      "JG004": [
        "JG004-1.jpg",
        "JG004-2.jpg",
        "JG004-3.jpg",
        "JG004-4.jpg",
        "JG004-5.jpg",
        "JG004-6.jpg"
      ],
      "JG005": [
        "JG005-1.jpg",
        "JG005-2.jpg",
        "JG005-3.jpg",
        "JG005-4.jpg",
        "JG005-5.jpg",
        "JG005-6.jpg"
      ]
    },
    "Kurta": {
      "KT001": [
        "KT001-1.jpg",
        "KT001-2.jpg",
        "KT001-3.jpg",
        "KT001-4.jpg",
        "KT001-5.jpg"
      ],
      "KT002": [
        "KT002-1.jpg",
        "KT002-2.jpg",
        "KT002-3.jpg",
        "KT002-4.jpg"
      ],
      "KT003": [
        "KT003-1.jpg",
        "KT003-2.jpg",
        "KT003-3.jpg",
        "KT003-4.jpg",
        "KT003-5.jpg"
      ],
      "KT004": [
        "KT004-1.jpg",
        "KT004-2.jpg",
        "KT004-3.jpg",
        "KT004-4.jpg"
      ],
      "KT005": [
        "KT005-1.jpg",
        "KT005-2.jpg",
        "KT005-3.jpg",
        "KT005-4.jpg"
      ],
      "KT006": [
        "KT006-1.jpg",
        "KT006-2.jpg",
        "KT006-3.jpg",
        "KT006-4.jpg"
      ],
      "KT007": [
        "KT007-1.jpg",
        "KT007-2.jpg",
        "KT007-3.jpg",
        "KT007-4.jpg",
        "KT007-5.jpg"
      ],
      "KT008": [
        "KT008-1.jpg",
        "KT008-2.jpg",
        "KT008-3.jpg",
        "KT008-4.jpg",
        "KT008-5.jpg"
      ]
    },
    "Oversized T-Shirts": {
      "OS001": [
        "OS001-1.jpg",
        "OS001-2.jpg",
        "OS001-3.jpg",
        "OS001-4.jpg"
      ],
      "OS002": [
        "OS002-1.jpg",
        "OS002-2.jpg",
        "OS002-3.jpg",
        "OS002-4.jpg",
        "OS002-5.jpg"
      ],
      "OS003": [
        "OS003-1.jpg",
        "OS003-2.jpg",
        "OS003-3.jpg",
        "OS003-4.jpg"
      ],
      "OS004": [
        "OS004-1.jpg",
        "OS004-2.jpg",
        "OS004-3.jpg",
        "OS004-4.jpg"
      ],
      "OS005": [
        "OS005-1.jpg",
        "OS005-2.jpg",
        "OS005-3.jpg",
        "OS005-4.jpg",
        "OS005-5.jpg"
      ],
      "OS006": [
        "OS006-1.jpg",
        "OS006-2.jpg",
        "OS006-3.jpg"
      ],
      "OS007": [
        "OS007-1.jpg",
        "OS007-2.jpg",
        "OS007-3.jpg",
        "OS007-4.jpg",
        "OS007-5.jpg",
        "OS007-6.jpg"
      ],
      "OS008": [
        "OS008-1.jpg",
        "OS008-2.jpg",
        "OS008-3.jpg",
        "OS008-4.jpg",
        "OS008-5.jpg",
        "OS008-6.jpg"
      ]
    },
    "polo-tshirts": {
      "PT001": [
        "PT001-1.jpg",
        "PT001-2.jpg",
        "PT001-3.jpg",
        "PT001-4.jpg",
        "PT001-5.jpg"
      ],
      "PT002": [
        "PT002-1.jpg",
        "PT002-2.jpg",
        "PT002-3.jpg",
        "PT002-4.jpg"
      ],
      "PT003": [
        "PT003-1.jpg",
        "PT003-2.jpg",
        "PT003-3.jpg",
        "PT003-4.jpg",
        "PT003-5.jpg",
        "PT003-6.jpg"
      ],
      "PT004": [
        "PT004-1.jpg",
        "PT004-2.jpg",
        "PT004-3.jpg",
        "PT004-4.jpg",
        "PT004-5.jpg"
      ],
      "PT005": [
        "PT005-1.jpg",
        "PT005-2.jpg",
        "PT005-3.jpg",
        "PT005-4.jpg",
        "PT005-5.jpg"
      ],
      "PT006": [
        "PT006-1.jpg",
        "PT006-2.jpg",
        "PT006-3.jpg",
        "PT006-4.jpg",
        "PT006-5.jpg",
        "PT006-6.jpg"
      ],
      "PT007": [
        "PT007-1.jpg",
        "PT007-2.jpg",
        "PT007-3.jpg",
        "PT007-4.jpg",
        "PT007-5.jpg",
        "PT007-6.jpg",
        "PT007-7.jpg"
      ],
      "PT008": [
        "PT008-1.jpg",
        "PT008-2.jpg",
        "PT008-3.jpg",
        "PT008-4.jpg",
        "PT008-5.jpg",
        "PT008-6.jpg"
      ],
      "PT009": [
        "PT009-1.jpg",
        "PT009-2.jpg",
        "PT009-3.jpg",
        "PT009-4.jpg",
        "PT009-5.jpg"
      ],
      "PT010": [
        "PT010-1.jpg",
        "PT010-2.jpg",
        "PT010-3.jpg",
        "PT010-4.jpg"
      ]
    },
    "Printed-Shirts": {
      "PS001": [
        "PS001-1.jpg",
        "PS001-2.jpg",
        "PS001-3.jpg",
        "PS001-4.jpg",
        "PS001-6.jpg"
      ],
      "PS002": [
        "PS002-1.jpg",
        "PS002-2.jpg",
        "PS002-3.jpg",
        "PS002-4.jpg"
      ],
      "PS003": [
        "PS003-1.jpg",
        "PS003-2.jpg",
        "PS003-3.jpg",
        "PS003-4.jpg",
        "PS003-5.jpg"
      ],
      "PS004": [
        "PS004-1.jpg",
        "PS004-2.jpg",
        "PS004-3.jpg",
        "PS004-4.jpg",
        "PS004-5.jpg",
        "PS004-6.jpg"
      ],
      "PS005": [
        "PS005-1.jpg",
        "PS005-2.jpg",
        "PS005-3.jpg",
        "PS005-4.jpg",
        "PS005-5.jpg"
      ],
      "PS006": [
        "PS006-1.jpg",
        "PS006-2.jpg",
        "PS006-3.jpg",
        "PS006-4.jpg",
        "PS006-5.jpg",
        "PS006-6.jpg"
      ],
      "PS007": [
        "PS007-1.jpg",
        "PS007-2.jpg",
        "PS007-3.jpg",
        "PS007-4.jpg",
        "PS007-5.jpg",
        "PS007-6.jpg",
        "PS007-7.jpg"
      ]
    },
    "Regular Jeans": {
      "RJ001": [
        "RJ001-1.jpg",
        "RJ001-2.jpg",
        "RJ001-3.jpg",
        "RJ001-4.jpg",
        "RJ001-5.jpg",
        "RJ001-6.jpg"
      ],
      "RJ002": [
        "RJ002-1.jpg",
        "RJ002-2.jpg",
        "RJ002-3.jpg",
        "RJ002-4.jpg",
        "RJ002-5.jpg",
        "RJ002-6.jpg"
      ],
      "RJ003": [
        "RJ003-1.jpg",
        "RJ003-2.jpg",
        "RJ003-3.jpg",
        "RJ003-4.jpg",
        "RJ003-5.jpg",
        "RJ003-6.jpg"
      ],
      "RJ004": [
        "RJ004-1.jpg",
        "RJ004-2.jpg",
        "RJ004-3.jpg",
        "RJ004-4.jpg",
        "RJ004-5.jpg",
        "RJ004-6.jpg"
      ],
      "RJ005": [
        "RJ005-1.jpg",
        "RJ005-2.jpg",
        "RJ005-3.jpg",
        "RJ005-4.jpg",
        "RJ005-5.jpg",
        "RJ005-6.jpg"
      ],
      "RJ006": [
        "RJ006-1.jpg",
        "RJ006-2.jpg",
        "RJ006-3.jpg",
        "RJ006-4.jpg",
        "RJ006-5.jpg",
        "RJ006-6.jpg"
      ],
      "RJ007": [
        "RJ007-1.jpg",
        "RJ007-2.jpg",
        "RJ007-3.jpg",
        "RJ007-4.jpg",
        "RJ007-5.jpg"
      ],
      "RJ008": [
        "RJ008-1.jpg",
        "RJ008-2.jpg",
        "RJ008-3.jpg",
        "RJ008-4.jpg",
        "RJ008-5.jpg",
        "RJ008-6.jpg"
      ]
    },
    "Round Neck T-Shirts": {
      "RN001": [
        "RN001-1.jpg",
        "RN001-2.jpg",
        "RN001-3.jpg",
        "RN001-4.jpg",
        "RN001-5.jpg"
      ],
      "RN002": [
        "RN002-1.jpg",
        "RN002-2.jpg",
        "RN002-3.jpg",
        "RN002-4.jpg",
        "RN002-5.jpg",
        "RN002-6.jpg"
      ],
      "RN003": [
        "RN003-1.jpg",
        "RN003-2.jpg",
        "RN003-3.jpg",
        "RN003-4.jpg"
      ],
      "RN004": [
        "RN004-1.jpg",
        "RN004-2.jpg",
        "RN004-3.jpg",
        "RN004-4.jpg"
      ],
      "RN005": [
        "RN005-1.jpg",
        "RN005-2.jpg",
        "RN005-3.jpg",
        "RN005-4.jpg",
        "RN005-5.jpg"
      ],
      "RN006": [
        "RN006-1.jpg",
        "RN006-2.jpg",
        "RN006-3.jpg",
        "RN006-4.jpg",
        "RN006-5.jpg"
      ],
      "RN007": [
        "RN007-1.jpg",
        "RN007-2.jpg",
        "RN007-3.jpg",
        "RN007-4.jpg",
        "RN007-5.jpg",
        "RN007-6.jpg"
      ],
      "RN008": [
        "RN008-1.jpg",
        "RN008-2.jpg"
      ]
    },
    "Sherwani": {
      "SHW001": [
        "SHW001-1.jpg",
        "SHW001-2.jpg",
        "SHW001-3.jpg"
      ],
      "SHW002": [
        "SHW002-1.jpg",
        "SHW002-2.jpg",
        "SHW002-3.jpg"
      ],
      "SHW003": [
        "SHW003-1.jpg",
        "SHW003-2.jpg",
        "SHW003-3.jpg",
        "SHW003-4.jpg"
      ],
      "SHW004": [
        "SHW004-1.jpg",
        "SHW004-2.jpg",
        "SHW004-3.jpg",
        "SHW004-4.jpg"
      ],
      "SHW005": [
        "SHW005-1.jpg",
        "SHW005-2.jpg",
        "SHW005-3.jpg",
        "SHW005-4.jpg"
      ],
      "SHW006": [
        "SHW006-1.jpg",
        "SHW006-2.jpg",
        "SHW006-3.jpg",
        "SHW006-4.jpg"
      ]
    },
    "Shorts": {
      "SH001": [
        "SH001-1.jpg",
        "SH001-2.jpg",
        "SH001-3.jpg",
        "SH001-4.jpg",
        "SH001-5.jpg",
        "SH001-6.jpg"
      ],
      "SH002": [
        "SH002-1.jpg",
        "SH002-2.jpg",
        "SH002-3.jpg",
        "SH002-4.jpg",
        "SH002-5.jpg",
        "SH002-6.jpg"
      ],
      "SH003": [
        "SH003-1.jpg",
        "SH003-2.jpg",
        "SH003-3.jpg",
        "SH003-4.jpg",
        "SH003-5.jpg"
      ],
      "SH004": [
        "SH004-1.jpg",
        "SH004-2.jpg",
        "SH004-3.jpg",
        "SH004-4.jpg",
        "SH004-5.jpg",
        "SH004-6.jpg"
      ],
      "SH005": [
        "SH005-1.jpg",
        "SH005-2.jpg",
        "SH005-3.jpg",
        "SH005-4.jpg",
        "SH005-5.jpg",
        "SH005-6.jpg"
      ],
      "SH006": [
        "SH006-1.jpg",
        "SH006-2.jpg",
        "SH006-3.jpg",
        "SH006-4.jpg",
        "SH006-5.jpg",
        "SH006-6.jpg"
      ],
      "SH007": [
        "SH007-1.jpg",
        "SH007-2.jpg",
        "SH007-3.jpg",
        "SH007-4.jpg",
        "SH007-5.jpg",
        "SH007-6.jpg"
      ],
      "SH008": [
        "SH008-1.jpg",
        "SH008-2.jpg",
        "SH008-3.jpg",
        "SH008-4.jpg"
      ],
      "SH009": [
        "SH009-1.jpg",
        "SH009-2.jpg",
        "SH009-3.jpg",
        "SH009-4.jpg",
        "SH009-5.jpg",
        "SH009-6.jpg"
      ],
      "SH010": [
        "SH010-1.jpg",
        "SH010-2.jpg",
        "SH010-3.jpg",
        "SH010-4.jpg",
        "SH010-5.jpg"
      ]
    },
    "Slim Jeans": {
      "SJ001": [
        "SJ001-1.jpg",
        "SJ001-2.jpg",
        "SJ001-3.jpg",
        "SJ001-4.jpg",
        "SJ001-5.jpg"
      ],
      "SJ002": [
        "SJ002-1.png",
        "SJ002-2.png",
        "SJ002-3.png",
        "SJ002-4.png"
      ],
      "SJ003": [
        "SJ003-1.webp",
        "SJ003-2.webp",
        "SJ003-3.webp",
        "SJ003-4.webp",
        "SJ003-5.webp",
        "SJ003-6.webp",
        "SJ003-7.webp"
      ],
      "SJ004": [
        "SJ004-1.avif",
        "SJ004-2.avif",
        "SJ004-3.avif",
        "SJ004-4.avif",
        "SJ004-5.avif"
      ],
      "SJ005": [
        "SJ005-1.avif",
        "SJ005-1.jpg",
        "SJ005-2.avif",
        "SJ005-2.jpg",
        "SJ005-3.avif",
        "SJ005-3.jpg",
        "SJ005-4.avif",
        "SJ005-4.jpg",
        "SJ005-5.avif",
        "SJ005-5.jpg",
        "SJ005-6.jpg"
      ],
      "SJ006": [
        "SJ006-1.jpg",
        "SJ006-2.jpg",
        "SJ006-3.jpg",
        "SJ006-4.jpg",
        "SJ006-5.jpg",
        "SJ006-6.jpg"
      ],
      "SJ007": [
        "SJ007-1.jpg",
        "SJ007-2.jpg",
        "SJ007-3.jpg",
        "SJ007-4.jpg",
        "SJ007-5.jpg",
        "SJ007-6.jpg"
      ],
      "SJ008": [
        "SJ008-1.jpg",
        "SJ008-2.jpg",
        "SJ008-3.jpg",
        "SJ008-4.jpg"
      ],
      "SJ009": [
        "SJ009-1.jpg",
        "SJ009-2.jpg",
        "SJ009-3.jpg",
        "SJ009-4.jpg",
        "SJ009-5.jpg",
        "SJ009-6.jpg",
        "SJ009-7.jpg"
      ],
      "SJ010": [
        "SJ010-1.jpg",
        "SJ010-2.jpg",
        "SJ010-3.jpg",
        "SJ010-4.jpg"
      ],
      "SJ011": [
        "SJ011-1.png",
        "SJ011-2.png",
        "SJ011-3.png",
        "SJ011-4.png"
      ],
      "SJ012": [
        "SJ012-1.png",
        "SJ012-2.png",
        "SJ012-3.png",
        "SJ012-4.png",
        "SJ012-5.png",
        "SJ012-6.png"
      ],
      "SJ013": [
        "SJ013-1.png",
        "SJ013-2.png",
        "SJ013-3.png",
        "SJ013-4.png",
        "SJ013-5.png"
      ]
    },
    "Solid-Shirts": {
      "SS001": [
        "SS001-1.jpg",
        "SS001-2.jpg",
        "SS001-3.jpg",
        "SS001-4.jpg",
        "SS001-5.jpg",
        "SS001-6.jpg"
      ],
      "SS002": [
        "SS002-1.jpg",
        "SS002-2.jpg",
        "SS002-3.jpg",
        "SS002-4.jpg",
        "SS002-5.jpg"
      ],
      "SS003": [
        "SS003-1.jpg",
        "SS003-2.jpg",
        "SS003-3.jpg",
        "SS003-4.jpg",
        "SS003-5.jpg"
      ],
      "SS004": [
        "SS004-1.jpg",
        "SS004-2.jpg",
        "SS004-3.jpg",
        "SS004-4.jpg",
        "SS004-5.jpg"
      ],
      "SS005": [
        "SS005-1.jpg",
        "SS005-2.jpg",
        "SS005-3.jpg",
        "SS005-4.jpg",
        "SS005-5.jpg",
        "SS005-6.jpg"
      ],
      "SS006": [
        "SS006-1.jpg",
        "SS006-2.jpg",
        "SS006-3.jpg",
        "SS006-4.jpg",
        "SS006-5.jpg",
        "SS006-6.jpg"
      ]
    },
    "Sweatshirts": {
      "SW001": [
        "SW001-1.jpg",
        "SW001-2.jpg"
      ],
      "SW002": [
        "SW002-1.jpg",
        "SW002-2.jpg",
        "SW002-3.jpg"
      ],
      "SW003": [
        "SW003-1.jpg",
        "SW003-2.jpg",
        "SW003-3.jpg",
        "SW003-4.jpg"
      ],
      "SW004": [
        "SW004-1.jpg",
        "SW004-2.jpg",
        "SW004-3.jpg",
        "SW004-4.jpg"
      ],
      "SW005": [
        "SW005-1.jpg",
        "SW005-2.jpg",
        "SW005-3.jpg",
        "SW005-4.jpg"
      ],
      "SW006": [
        "SW006-1.jpg",
        "SW006-2.jpg",
        "SW006-3.jpg",
        "SW006-4.jpg",
        "SW006-5.jpg"
      ]
    },
    "tshirts": {
      "TS001": [
        "TS001.webp"
      ],
      "TS002": [
        "TS002.webp"
      ]
    },
    "Vests": {
      "VS001": [
        "VS001-1.jpg",
        "VS001-2.jpg"
      ],
      "VS002": [
        "VS002-1.jpg",
        "VS002-2.jpg"
      ],
      "VS003": [
        "VS003.jpg"
      ],
      "VS004": [
        "VS004.jpg"
      ],
      "VS005": [
        "VS005.jpg"
      ]
    }
  }
};
