/**
 * Scans public/images/products/<gender>/<folder>/ and groups files into per-product photo
 * sets — e.g. FS001-1.jpg..FS001-5.jpg become one product's ordered gallery (FS001-1 first/
 * main), while a lone CS001.webp becomes a single-image product. Writes the result to
 * src/data/productImageManifest.ts, a plain data module safe to import from both the browser
 * bundle and the Node seed script (see src/lib/productImages.ts, which is intentionally
 * environment-agnostic for the same reason).
 *
 * Runs automatically before `npm run dev` / `npm run build` (see package.json "predev"/
 * "prebuild"), or by hand whenever files under public/images/products/ change:
 *   npm run images:scan
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PRODUCTS_DIR = path.join(ROOT, 'public/images/products');
const OUT_FILE = path.join(ROOT, 'src/data/productImageManifest.ts');

/** Matches "FS001-1.jpg" (code=FS001, index=1) and "CS001.webp" (code=CS001, index defaults to 1). */
const FILENAME_PATTERN = /^([A-Za-z]+\d+)(?:-(\d+))?\.\w+$/;

function scanCategoryFolder(dirPath: string): Record<string, string[]> {
  const groups: Record<string, { index: number; file: string }[]> = {};
  let entries: string[] = [];
  try {
    entries = fs.readdirSync(dirPath);
  } catch {
    return {};
  }

  for (const entry of entries) {
    const match = FILENAME_PATTERN.exec(entry);
    if (!match) continue;
    const [, code, indexStr] = match;
    const index = indexStr ? Number(indexStr) : 1;
    (groups[code] ??= []).push({ index, file: entry });
  }

  const result: Record<string, string[]> = {};
  for (const [code, files] of Object.entries(groups)) {
    result[code] = files.sort((a, b) => a.index - b.index).map((f) => f.file);
  }
  return result;
}

function scanAll(): Record<string, Record<string, Record<string, string[]>>> {
  const manifest: Record<string, Record<string, Record<string, string[]>>> = {};
  if (!fs.existsSync(PRODUCTS_DIR)) return manifest;

  for (const gender of fs.readdirSync(PRODUCTS_DIR)) {
    const genderDir = path.join(PRODUCTS_DIR, gender);
    if (!fs.statSync(genderDir).isDirectory()) continue;

    for (const folder of fs.readdirSync(genderDir)) {
      const folderDir = path.join(genderDir, folder);
      if (!fs.statSync(folderDir).isDirectory()) continue;

      const groups = scanCategoryFolder(folderDir);
      if (Object.keys(groups).length === 0) continue;
      manifest[gender] ??= {};
      manifest[gender][folder] = groups;
    }
  }
  return manifest;
}

const manifest = scanAll();
const productPhotoSetCount = Object.values(manifest).reduce(
  (sum, folders) => sum + Object.values(folders).reduce((s, codes) => s + Object.keys(codes).length, 0),
  0,
);
const fileCount = Object.values(manifest).reduce(
  (sum, folders) => sum + Object.values(folders).reduce((s, codes) => s + Object.values(codes).reduce((n, files) => n + files.length, 0), 0),
  0,
);

const banner =
  '/**\n' +
  ' * AUTO-GENERATED by scripts/generateImageManifest.ts — do not edit by hand.\n' +
  ' * Regenerate with `npm run images:scan` (also runs automatically before dev/build)\n' +
  ' * whenever files under public/images/products/ change.\n' +
  ' */\n';
const body = `export const PRODUCT_IMAGE_MANIFEST: Record<string, Record<string, Record<string, string[]>>> = ${JSON.stringify(manifest, null, 2)};\n`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, banner + body);
console.log(`✔ Scanned public/images/products/ — ${productPhotoSetCount} product photo set(s), ${fileCount} file(s) → ${path.relative(ROOT, OUT_FILE)}`);
