/**
 * AUTO-GENERATED by scripts/generateImageManifest.ts — do not edit by hand.
 * Regenerate with `npm run images:scan` (also runs automatically before dev/build)
 * whenever files under public/images/products/ change.
 */
export const PRODUCT_IMAGE_MANIFEST: Record<string, Record<string, Record<string, string[]>>> = {
  "men": {
    "casual-shirts": {
      "CS001": [
        "CS001.webp"
      ]
    },
    "checked-shirts": {
      "CHS001": [
        "CHS001-1.jpg",
        "CHS001-2.jpg",
        "CHS001-3.jpg",
        "CHS001-4.jpg",
        "CHS001-5.jpg",
        "CHS001-6.jpg",
        "CHS001-7.jpg"
      ],
      "CHS002": [
        "CHS002-1.jpg",
        "CHS002-2.jpg",
        "CHS002-3.jpg",
        "CHS002-4.jpg",
        "CHS002-5.jpg",
        "CHS002-6.jpg"
      ],
      "CHS003": [
        "CHS003-1.jpg",
        "CHS003-2.jpg",
        "CHS003-3.jpg",
        "CHS003-4.jpg",
        "CHS003-5.jpg",
        "CHS003-6.jpg"
      ],
      "CHS004": [
        "CHS004-1.jpg",
        "CHS004-2.jpg",
        "CHS004-3.jpg",
        "CHS004-4.jpg",
        "CHS004-5.jpg",
        "CHS004-6.jpg"
      ],
      "CHS005": [
        "CHS005-1.jpg",
        "CHS005-2.jpg",
        "CHS005-3.jpg",
        "CHS005-4.jpg",
        "CHS005-5.jpg",
        "CHS005-6.jpg"
      ],
      "CHS006": [
        "CHS006-1.jpg",
        "CHS006-2.jpg",
        "CHS006-3.jpg",
        "CHS006-4.jpg",
        "CHS006-5.jpg"
      ],
      "CHS007": [
        "CHS007-1.jpg",
        "CHS007-2.jpg",
        "CHS007-3.jpg",
        "CHS007-4.jpg",
        "CHS007-5.jpg"
      ],
      "CHS008": [
        "CHS008-1.jpg",
        "CHS008-2.jpg",
        "CHS008-3.jpg",
        "CHS008-4.jpg",
        "CHS008-5.jpg",
        "CHS008-6.jpg"
      ],
      "CHS009": [
        "CHS009-1.jpg",
        "CHS009-2.jpg",
        "CHS009-3.jpg",
        "CHS009-4.jpg",
        "CHS009-5.jpg"
      ],
      "CHS010": [
        "CHS010-1.jpg",
        "CHS010-2.jpg",
        "CHS010-3.jpg",
        "CHS010-4.jpg",
        "CHS010-5.jpg",
        "CHS010-6.jpg"
      ],
      "CHS011": [
        "CHS011-1.jpg",
        "CHS011-2.jpg",
        "CHS011-3.jpg",
        "CHS011-4.jpg",
        "CHS011-5.jpg",
        "CHS011-6.jpg"
      ],
      "CHS012": [
        "CHS012-1.jpg",
        "CHS012-2.jpg",
        "CHS012-3.jpg",
        "CHS012-4.jpg",
        "CHS012-5.jpg"
      ],
      "CHS013": [
        "CHS013-1.jpg",
        "CHS013-2.jpg",
        "CHS013-3.jpg",
        "CHS013-4.jpg",
        "CHS013-5.jpg"
      ],
      "CHS014": [
        "CHS014-1.jpg",
        "CHS014-2.jpg",
        "CHS014-3.jpg",
        "CHS014-4.jpg",
        "CHS014-5.jpg"
      ],
      "CHS016": [
        "CHS016-1.jpg",
        "CHS016-2.jpg",
        "CHS016-3.jpg",
        "CHS016-4.jpg",
        "CHS016-5.jpg",
        "CHS016-6.jpg"
      ],
      "CHS017": [
        "CHS017-1.jpg",
        "CHS017-2.jpg",
        "CHS017-3.jpg",
        "CHS017-4.jpg",
        "CHS017-5.jpg",
        "CHS017-6.jpg"
      ],
      "CHS018": [
        "CHS018-1.jpg",
        "CHS018-2.jpg",
        "CHS018-3.jpg",
        "CHS018-4.jpg",
        "CHS018-5.jpg"
      ],
      "CHS019": [
        "CHS019-1.jpg",
        "CHS019-2.jpg",
        "CHS019-3.jpg",
        "CHS019-4.jpg",
        "CHS019-5.jpg",
        "CHS019-6.jpg",
        "CHS019-7.jpg"
      ],
      "CHS020": [
        "CHS020-1.jpg",
        "CHS020-2.jpg",
        "CHS020-3.jpg",
        "CHS020-4.jpg",
        "CHS020-5.jpg"
      ],
      "CHS021": [
        "CHS021-1.jpg",
        "CHS021-2.jpg",
        "CHS021-3.jpg",
        "CHS021-4.jpg",
        "CHS021-5.jpg"
      ],
      "CHS022": [
        "CHS022-1.jpg",
        "CHS022-2.jpg",
        "CHS022-3.jpg",
        "CHS022-4.jpg",
        "CHS022-5.jpg"
      ],
      "CHS023": [
        "CHS023-1.jpg",
        "CHS023-2.jpg",
        "CHS023-3.jpg",
        "CHS023-4.jpg",
        "CHS023-5.jpg",
        "CHS023-6.jpg"
      ],
      "CHS024": [
        "CHS024-1.jpg",
        "CHS024-2.jpg",
        "CHS024-3.jpg",
        "CHS024-4.jpg",
        "CHS024-5.jpg"
      ],
      "CHS025": [
        "CHS025-1.jpg",
        "CHS025-2.jpg",
        "CHS025-3.jpg",
        "CHS025-4.jpg",
        "CHS025-5.jpg",
        "CHS025-6.jpg"
      ],
      "CHS026": [
        "CHS026-1.jpg",
        "CHS026-2.jpg",
        "CHS026-3.jpg",
        "CHS026-4.jpg"
      ],
      "CHS027": [
        "CHS027-1.jpg",
        "CHS027-2.jpg",
        "CHS027-3.jpg",
        "CHS027-4.jpg",
        "CHS027-5.jpg"
      ],
      "CHS028": [
        "CHS028-1.jpg",
        "CHS028-2.jpg",
        "CHS028-3.jpg",
        "CHS028-4.jpg",
        "CHS028-5.jpg",
        "CHS028-6.jpg"
      ],
      "CHS029": [
        "CHS029-1.jpg",
        "CHS029-2.jpg",
        "CHS029-3.jpg",
        "CHS029-4.jpg",
        "CHS029-5.jpg"
      ],
      "CHS030": [
        "CHS030-1.jpg",
        "CHS030-2.jpg"
      ]
    },
    "formal-shirts": {
      "FS001": [
        "FS001-1.webp",
        "FS001-2.webp",
        "FS001-3.webp",
        "FS001-4.webp"
      ],
      "FS002": [
        "FS002-1.webp",
        "FS002-2.webp",
        "FS002-3.webp",
        "FS002-4.webp"
      ],
      "FS003": [
        "FS003-1.webp",
        "FS003-2.webp",
        "FS003-3.webp",
        "FS003-4.webp",
        "FS003-5.webp",
        "FS003-6.webp"
      ],
      "FS004": [
        "FS004-1.jpeg",
        "FS004-2.jpeg",
        "FS004-3.jpeg",
        "FS004-4.jpeg"
      ],
      "FS007": [
        "FS007-1.jpg",
        "FS007-2.jpg",
        "FS007-3.jpg",
        "FS007-4.jpg",
        "FS007-5.jpg"
      ],
      "FS008": [
        "FS008-1.jpg",
        "FS008-2.jpg",
        "FS008-3.jpg",
        "FS008-4.jpg"
      ],
      "FS009": [
        "FS009-1.jpg",
        "FS009-2.jpg",
        "FS009-3.jpg",
        "FS009-4.jpg",
        "FS009-5.jpg"
      ],
      "FS010": [
        "FS010-1.jpg",
        "FS010-2.jpg",
        "FS010-3.jpg",
        "FS010-4.jpg",
        "FS010-5.jpg"
      ],
      "FS011": [
        "FS011-1.jpg",
        "FS011-2.jpg",
        "FS011-3.jpg",
        "FS011-4.jpg",
        "FS011-5.jpg",
        "FS011-6.jpg"
      ],
      "FS014": [
        "FS014-1.jpg",
        "FS014-2.jpg",
        "FS014-3.jpg",
        "FS014-4.jpg",
        "FS014-5.jpg"
      ],
      "FS015": [
        "FS015-1.jpg",
        "FS015-2.jpg",
        "FS015-3.jpg",
        "FS015-4.jpg"
      ],
      "FS016": [
        "FS016-1.jpg",
        "FS016-2.jpg",
        "FS016-3.jpg",
        "FS016-4.jpg",
        "FS016-5.png",
        "FS016-6.png"
      ],
      "FS017": [
        "FS017-2.jpg",
        "FS017-3.jpg",
        "FS017-4.jpg",
        "FS017-5.jpg"
      ],
      "FS019": [
        "FS019-1.jpg",
        "FS019-2.jpg",
        "FS019-3.jpg"
      ],
      "FS020": [
        "FS020-1.jpg",
        "FS020-2.jpg",
        "FS020-3.jpg",
        "FS020-4.jpg"
      ],
      "FS021": [
        "FS021-1.webp",
        "FS021-2.webp",
        "FS021-3.webp"
      ],
      "FS023": [
        "FS023-1.png",
        "FS023-2.png",
        "FS023-3.png",
        "FS023-4.png",
        "FS023-5.png",
        "FS023-6.png"
      ],
      "FS024": [
        "FS024-1.png",
        "FS024-2.png",
        "FS024-3.png",
        "FS024-4.png",
        "FS024-5.png"
      ],
      "FS025": [
        "FS025-1.png",
        "FS025-2.png",
        "FS025-3.png",
        "FS025-4.png"
      ],
      "FS026": [
        "FS026-1.png",
        "FS026-2.png",
        "FS026-3.png"
      ],
      "FS027": [
        "FS027-1.png",
        "FS027-2.png",
        "FS027-3.png",
        "FS027-4.png",
        "FS027-5.png",
        "FS027-6.png"
      ],
      "FS028": [
        "FS028-1.png",
        "FS028-2.png",
        "FS028-3.png",
        "FS028-4.png",
        "FS028-5.png"
      ],
      "FS029": [
        "FS029-1.png",
        "FS029-2.png",
        "FS029-3.png",
        "FS029-4.png",
        "FS029-5.png",
        "FS029-6.png"
      ],
      "FS030": [
        "FS030-1.png",
        "FS030-2.png",
        "FS030-3.png",
        "FS030-4.png",
        "FS030-5.png"
      ],
      "FS031": [
        "FS031-1.jpg",
        "FS031-2.jpg",
        "FS031-3.jpg",
        "FS031-4.jpg",
        "FS031-5.jpg",
        "FS031-6.jpg"
      ],
      "FS032": [
        "FS032-1.jpg",
        "FS032-2.jpg",
        "FS032-3.jpg",
        "FS032-4.jpg",
        "FS032-5.jpg"
      ],
      "FS033": [
        "FS033-1.jpg",
        "FS033-2.jpg",
        "FS033-3.jpg",
        "FS033-4.jpg",
        "FS033-5.jpg",
        "FS033-6.jpg"
      ],
      "FS034": [
        "FS034-1.jpg",
        "FS034-2.jpg",
        "FS034-3.jpg",
        "FS034-4.jpg",
        "FS034-5.jpg",
        "FS034-6.jpg"
      ],
      "FS035": [
        "FS035-1.jpg",
        "FS035-2.jpg",
        "FS035-3.jpg",
        "FS035-4.jpg",
        "FS035-5.jpg",
        "FS035-6.jpg"
      ],
      "FS036": [
        "FS036-1.jpg",
        "FS036-2.jpg",
        "FS036-3.jpg",
        "FS036-4.jpg",
        "FS036-5.jpg",
        "FS036-6.jpg",
        "FS036-7.jpg"
      ],
      "FS037": [
        "FS037-1.jpg",
        "FS037-2.jpg",
        "FS037-3.jpg",
        "FS037-4.jpg",
        "FS037-5.jpg",
        "FS037-6.jpg",
        "FS037-7.jpg"
      ],
      "FS038": [
        "FS038-1.jpg",
        "FS038-2.jpg",
        "FS038-3.jpg",
        "FS038-4.jpg",
        "FS038-5.jpg",
        "FS038-6.jpg"
      ],
      "FS039": [
        "FS039-1.jpg",
        "FS039-2.jpg",
        "FS039-3.jpg",
        "FS039-4.jpg",
        "FS039-5.jpg",
        "FS039-6.jpg",
        "FS039-7.jpg"
      ],
      "FS040": [
        "FS040-1.jpg",
        "FS040-2.jpg",
        "FS040-3.jpg",
        "FS040-4.jpg",
        "FS040-5.jpg",
        "FS040-6.jpg",
        "FS040-7.jpg"
      ],
      "FS041": [
        "FS041-1.jpg",
        "FS041-2.jpg",
        "FS041-3.jpg",
        "FS041-4.jpg",
        "FS041-5.jpg",
        "FS041-6.jpg",
        "FS041-7.jpg"
      ],
      "FS042": [
        "FS042-1.jpg",
        "FS042-2.jpg",
        "FS042-3.jpg",
        "FS042-4.jpg",
        "FS042-5.jpg",
        "FS042-6.jpg",
        "FS042-7.jpg"
      ],
      "FS043": [
        "FS043-1.jpg",
        "FS043-2.jpg",
        "FS043-3.jpg",
        "FS043-4.jpg",
        "FS043-5.jpg",
        "FS043-6.jpg"
      ],
      "FS044": [
        "FS044-1.jpg",
        "FS044-2.jpg",
        "FS044-3.jpg",
        "FS044-4.jpg"
      ],
      "FS045": [
        "FS045-1.jpg",
        "FS045-3.jpg",
        "FS045-4.jpg",
        "FS045-5.jpg"
      ],
      "FS046": [
        "FS046-1.jpg",
        "FS046-2.jpg",
        "FS046-3.jpg",
        "FS046-4.jpg",
        "FS046-5.jpg"
      ],
      "FS047": [
        "FS047-1.jpg",
        "FS047-2.jpg",
        "FS047-3.jpg",
        "FS047-4.jpg"
      ],
      "FS048": [
        "FS048-1.jpg",
        "FS048-2.jpg",
        "FS048-3.jpg",
        "FS048-4.jpg"
      ],
      "FS049": [
        "FS049-1.jpg",
        "FS049-2.jpg",
        "FS049-3.jpg",
        "FS049-4.jpg",
        "FS049-5.jpg",
        "FS049-6.jpg"
      ],
      "FS050": [
        "FS050-1.jpg",
        "FS050-2.jpg",
        "FS050-3.jpg",
        "FS050-5.jpg"
      ],
      "FS051": [
        "FS051-1.jpg",
        "FS051-2.jpg",
        "FS051-3.jpg",
        "FS051-4.jpg",
        "FS051-5.jpg"
      ],
      "FS052": [
        "FS052-1.jpg",
        "FS052-2.jpg",
        "FS052-3.jpg",
        "FS052-4.jpg"
      ],
      "FS053": [
        "FS053-1.jpg",
        "FS053-2.jpg",
        "FS053-4.jpg",
        "FS053-5.jpg",
        "FS053-6.jpg"
      ],
      "FS054": [
        "FS054-1.jpg",
        "FS054-2.jpg",
        "FS054-3.jpg",
        "FS054-4.jpg"
      ],
      "FS055": [
        "FS055-1.jpg",
        "FS055-2.jpg",
        "FS055-3.jpg",
        "FS055-4.jpg",
        "FS055-5.jpg",
        "FS055-6.jpg"
      ],
      "FS056": [
        "FS056-1.jpg",
        "FS056-2.jpg",
        "FS056-3.jpg",
        "FS056-4.jpg",
        "FS056-5.jpg",
        "FS056-6.jpg"
      ],
      "FS057": [
        "FS057-1.jpg",
        "FS057-2.jpg",
        "FS057-3.jpg",
        "FS057-4.jpg",
        "FS057-5.jpg",
        "FS057-6.jpg",
        "FS057-7.jpg"
      ],
      "FS058": [
        "FS058-1.jpg",
        "FS058-3.jpg",
        "FS058-4.jpg"
      ],
      "FS059": [
        "FS059-1.jpg",
        "FS059-2.jpg",
        "FS059-3.jpg",
        "FS059-4.jpg",
        "FS059-5.jpg",
        "FS059-6.jpg",
        "FS059-8.jpg"
      ],
      "FS060": [
        "FS060-1.jpg",
        "FS060-2.jpg",
        "FS060-3.jpg",
        "FS060-4.jpg"
      ],
      "FS061": [
        "FS061-1.jpg",
        "FS061-2.jpg",
        "FS061-3.jpg"
      ],
      "FS062": [
        "FS062-1.jpg",
        "FS062-2.jpg",
        "FS062-3.jpg"
      ],
      "FS063": [
        "FS063-1.jpg",
        "FS063-2.jpg",
        "FS063-3.jpg",
        "FS063-4.jpg",
        "FS063-5.jpg"
      ],
      "FS064": [
        "FS064-1.jpg",
        "FS064-2.jpg",
        "FS064-3.jpg",
        "FS064-4.jpg"
      ],
      "FS065": [
        "FS065-1.jpg",
        "FS065-2.jpg",
        "FS065-3.jpg",
        "FS065-4.jpg",
        "FS065-5.jpg"
      ],
      "FS066": [
        "FS066-1.jpg",
        "FS066-2.jpg",
        "FS066-3.jpg",
        "FS066-4.jpg",
        "FS066-5.jpg",
        "FS066-6.jpg"
      ],
      "FS067": [
        "FS067-1.jpg",
        "FS067-2.jpg",
        "FS067-3.jpg",
        "FS067-4.jpg",
        "FS067-5.jpg"
      ],
      "FS068": [
        "FS068-1.jpg",
        "FS068-2.jpg",
        "FS068-3.jpg",
        "FS068-4.jpg"
      ],
      "FS069": [
        "FS069-1.jpg",
        "FS069-2.jpg",
        "FS069-3.jpg",
        "FS069-4.jpg",
        "FS069-5.jpg"
      ],
      "FS070": [
        "FS070-1.jpg",
        "FS070-2.jpg",
        "FS070-3.jpg",
        "FS070-4.jpg",
        "FS070-5.jpg",
        "FS070-6.jpg",
        "FS070-7.jpg"
      ],
      "FS071": [
        "FS071-1.jpg",
        "FS071-2.jpg",
        "FS071-3.jpg",
        "FS071-4.jpg",
        "FS071-5.jpg"
      ],
      "FS072": [
        "FS072-1.jpg",
        "FS072-2.jpg",
        "FS072-3.jpg",
        "FS072-4.jpg",
        "FS072-5.jpg"
      ],
      "FS073": [
        "FS073-1.jpg",
        "FS073-2.jpg",
        "FS073-3.jpg",
        "FS073-4.jpg",
        "FS073-5.jpg",
        "FS073-6.jpg"
      ]
    },
    "hoodies": {
      "HD001": [
        "HD001.webp"
      ]
    },
    "jackets": {
      "JK001": [
        "JK001.webp"
      ]
    },
    "jeans": {
      "JN001": [
        "JN001.webp"
      ]
    },
    "polo-tshirts": {
      "PT001": [
        "PT001.webp"
      ]
    },
    "tshirts": {
      "TS001": [
        "TS001.webp"
      ],
      "TS002": [
        "TS002.webp"
      ]
    }
  }
};
